name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - 'l10n*'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Fabric build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immersive-machinery-fabric
          path: fabric/build/libs/*.jar
      - name: Upload Forge build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immersive-machinery-forge
          path: forge/build/libs/*.jar
